--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.1.22.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 01/02/2019 21:05:47
-- Server version: 5.5.5-10.1.37-MariaDB
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE mycliente;

--
-- Drop table `acesso`
--
DROP TABLE IF EXISTS acesso;

--
-- Drop table `clientes`
--
DROP TABLE IF EXISTS clientes;

--
-- Drop table `enderecocliente`
--
DROP TABLE IF EXISTS enderecocliente;

--
-- Drop table `tipoendereco`
--
DROP TABLE IF EXISTS tipoendereco;

--
-- Drop table `telefonecliente`
--
DROP TABLE IF EXISTS telefonecliente;

--
-- Drop table `tipotelefone`
--
DROP TABLE IF EXISTS tipotelefone;

--
-- Set default database
--
USE mycliente;

--
-- Create table `tipotelefone`
--
CREATE TABLE tipotelefone (
  cptipotelefone INT(11) NOT NULL AUTO_INCREMENT,
  tipotelefone VARCHAR(20) NOT NULL,
  datacadtipotelefone DATETIME NOT NULL,
  PRIMARY KEY (cptipotelefone)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci,
COMMENT = 'Responsável por armazenar os tipos de telefone.';

--
-- Create table `telefonecliente`
--
CREATE TABLE telefonecliente (
  cpcodtelefonecliente INT(11) NOT NULL AUTO_INCREMENT,
  cetipotelefonecliente INT(11) NOT NULL,
  telfixo VARCHAR(13) DEFAULT NULL,
  telmovel VARCHAR(14) DEFAULT NULL,
  telcomercial VARCHAR(13) DEFAULT NULL,
  telrecado VARCHAR(14) DEFAULT NULL,
  datacadtelefonecliente DATETIME NOT NULL,
  PRIMARY KEY (cpcodtelefonecliente)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci,
COMMENT = 'Responsável por armazenar os telefones dos clientes.';

--
-- Create foreign key
--
ALTER TABLE telefonecliente 
  ADD CONSTRAINT FK_telefonecliente_cetipotelefonecliente FOREIGN KEY (cetipotelefonecliente)
    REFERENCES tipotelefone(cptipotelefone) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create table `tipoendereco`
--
CREATE TABLE tipoendereco (
  cpcodtipoendereco INT(11) NOT NULL AUTO_INCREMENT,
  tipoendereco VARCHAR(20) NOT NULL,
  datacadtipoendereco DATETIME NOT NULL,
  PRIMARY KEY (cpcodtipoendereco)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci,
COMMENT = 'Responsável por armazenar os tipos de endereço.';

--
-- Create table `enderecocliente`
--
CREATE TABLE enderecocliente (
  cpcodendcliente INT(11) NOT NULL AUTO_INCREMENT,
  cetipoendereco INT(11) NOT NULL,
  logradouro VARCHAR(100) NOT NULL,
  numeroendereco INT(11) NOT NULL,
  cep VARCHAR(9) NOT NULL,
  datacadendereco DATETIME NOT NULL,
  PRIMARY KEY (cpcodendcliente)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci,
COMMENT = 'Responsável por armazenar o endereço dos clientes cadastrados';

--
-- Create foreign key
--
ALTER TABLE enderecocliente 
  ADD CONSTRAINT FK_enderecocliente_cetipoendereco FOREIGN KEY (cetipoendereco)
    REFERENCES tipoendereco(cpcodtipoendereco) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create table `clientes`
--
CREATE TABLE clientes (
  cpcliente INT(11) NOT NULL AUTO_INCREMENT,
  ceenderecocliente INT(11) NOT NULL,
  cetelefonecliente INT(11) NOT NULL,
  nomecliente VARCHAR(100) NOT NULL,
  sexocliente CHAR(2) NOT NULL,
  cpfcliente CHAR(14) NOT NULL,
  rgcliente CHAR(12) NOT NULL,
  PRIMARY KEY (cpcliente)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci,
COMMENT = 'Responsável por armazenar os dados clientes.';

--
-- Create foreign key
--
ALTER TABLE clientes 
  ADD CONSTRAINT FK_clientes_ceendereco FOREIGN KEY (ceenderecocliente)
    REFERENCES enderecocliente(cpcodendcliente) ON DELETE CASCADE;

--
-- Create foreign key
--
ALTER TABLE clientes 
  ADD CONSTRAINT FK_clientes_telefone FOREIGN KEY (cetelefonecliente)
    REFERENCES telefonecliente(cpcodtelefonecliente) ON DELETE CASCADE;

--
-- Create table `acesso`
--
CREATE TABLE acesso (
  cpcodacesso INT(11) NOT NULL AUTO_INCREMENT,
  senha VARCHAR(255) DEFAULT NULL,
  dataacesso DATETIME DEFAULT NULL,
  PRIMARY KEY (cpcodacesso)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci,
COMMENT = 'Tabela responsável por armazenar a senhas de acesso ao sistema';

-- 
-- Dumping data for table tipotelefone
--
-- Table mycliente.tipotelefone does not contain any data (it is empty)

-- 
-- Dumping data for table tipoendereco
--
-- Table mycliente.tipoendereco does not contain any data (it is empty)

-- 
-- Dumping data for table telefonecliente
--
-- Table mycliente.telefonecliente does not contain any data (it is empty)

-- 
-- Dumping data for table enderecocliente
--
-- Table mycliente.enderecocliente does not contain any data (it is empty)

-- 
-- Dumping data for table clientes
--
-- Table mycliente.clientes does not contain any data (it is empty)

-- 
-- Dumping data for table acesso
--
-- Table mycliente.acesso does not contain any data (it is empty)

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;